# Generated by Django 4.2.28 on 2026-02-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='game_type',
            field=models.CharField(default='gomoku', max_length=20, verbose_name='游戏类型'),
        ),
    ]
