# Generated by Django 4.2.28 on 2026-03-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='note_images/', verbose_name='图片'),
        ),
    ]
