# Generated by Django 4.2.28 on 2026-03-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='是否在线'),
        ),
    ]
