# Generated by Django 4.2.28 on 2026-03-23 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0006_profile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_notes', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
        ),
    ]
