# Generated by Django 4.2.28 on 2026-03-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_stickynote_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='rotation',
            field=models.FloatField(default=0.0, verbose_name='旋转角度'),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='x_position',
            field=models.FloatField(default=10.0, verbose_name='横向位置(%)'),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='y_position',
            field=models.FloatField(default=10.0, verbose_name='纵向位置(%)'),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='z_index',
            field=models.IntegerField(default=1, verbose_name='层级/堆叠顺序'),
        ),
    ]
